### ISSUE TITLE
只能针对harbor2.x版本测试吗

### ISSUE THREAD

**Issue by lijianfeng1993** [goharbor/perf#33]
测试harbor1.9.2版本
go run mage.go prepare的时候报错
INFO[0003] GoError: failed to create project project-068, error: response status code does not match any response statuses defined for this endpoint in the swagger spec (status 404): {}  source=console
go run mage.go run pull-artifacts-from-same-project的时候报错
ERRO[0004] GoError: failed to push xxxxx/project-058/repository-1641782069696:tag-1641782069696, error: server message: insufficient_scope: authorization failed

测试harbor2.2.1是正常的

**Comment by Jeremy-boo** [comment]
yes, this project is currently only applicable to harbor 2.2 and above
