### ISSUE TITLE
Why does it take less time to push artifacts to different projects than to the same project?

### ISSUE THREAD

**Issue by jerryqzhang** [goharbor/perf#44]
https://github.com/goharbor/perf/wiki/Harbor-2.5.0
![image](https://github.com/goharbor/perf/assets/30404657/0db9aba9-fc03-4bad-84f8-8e257c1e016a)

**Comment by chlins** [comment]
Because each project is quota limited, there is an additional lock cost for checking and updating quotas when a large number of concurrent pushes to the same project.
